export const enum CatalogReducerActionTypesEnum {
    SET_PRODUCTS='SET_PRODUCTS',
    SET_USERS='SET_USERS',
    SET_FILTER='SET_FILTER',
    SET_SELECTED_PRODUCT_FOR_MODAL='SET_SELECTED_PRODUCT_FOR_MODAL',
    SET_USERS_LOADING_STATUS='SET_USERS_LOADING_STATUS',
    SET_REVIEWS='SET_REVIEWS'
}